Removed typos 'f' from the f-string error messages (#851)
Summary:
Changed mistake in Python f-strings causing an additional letter "f" to appear in the error messages.
The error messages would read something like :
```
raise ValueError(f"Invalid rotation matrix  shape f{matrix.shape}.")
ValueError: Invalid rotation matrix  shape ftorch.Size([4, 4]).
```
(with an additional f, probably a mistake)

Pull Request resolved: https://github.com/facebookresearch/pytorch3d/pull/851

Reviewed By: nikhilaravi

Differential Revision: D31238831

Pulled By: patricklabatut

fbshipit-source-id: 0ba3e61e488e467e997954278097889be606d4f8